[package]
name = "blip"
version = "0.1.0"
authors = ["Isaac Evavold <isaacevavold@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde_json="1.0"
